var horarios = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    var helper, alias1=helpers.helperMissing, alias2="function", alias3=this.escapeExpression;

  return "﻿<link href=\"css/fullcalendar.min.css\" rel=\"stylesheet\" />\r\n<script src=\"js/moment.min.js\"></script>\r\n<script src=\"js/fullcalendar.js\"></script>\r\n<script src=\"js/calendar.js\"></script>\r\n<script src=\"js/lang/es.js\"></script>\r\n<section id=\"directorio\">\r\n    <div class=\"container\">\r\n        <div class=\"row\">\r\n            <div class=\"panel\">\r\n                <div class=\"panel-body\">\r\n                    <h4>"
    + alias3(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"title","hash":{},"data":data}) : helper)))
    + "</h4>\r\n                    <div id=\"horarios\">\r\n                        <form method=\"POST\" name=\"frmRegHorarios\" id=\"frmRegHorarios\">\r\n                            <input type=\"hidden\" id=\"direccion_id\" name=\"direccion_id\" value=\""
    + alias3(((helper = (helper = helpers.direccion_id || (depth0 != null ? depth0.direccion_id : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"direccion_id","hash":{},"data":data}) : helper)))
    + "\" />\r\n                            <input type=\"hidden\" id=\"horariosUbi\" name=\"horariosUbi\" value=\""
    + alias3(((helper = (helper = helpers.horarios || (depth0 != null ? depth0.horarios : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"horarios","hash":{},"data":data}) : helper)))
    + "\" />\r\n                            <div class=\"row\">\r\n                                <div class=\"col-md-12\"><div id='calendar'></div></div>\r\n                                <div class=\"col-md-6\">\r\n                                    <div id=\"calendarTrash\">\r\n                                        <img src=\"img/eliminar.png\" />\r\n                                    </div>\r\n                                </div>\r\n                                <div class=\"col-md-6\"><input type=\"button\" class=\"btn btn-info btn-md btn-block\" id=\"btnRegHorarios\" value=\"Guardar Horarios\" onclick=\"regHorarios()\"></div>\r\n                            </div>\r\n                        </form>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>";
},"useData":true});